#!/bin/bash
# fetch-prod-cidrs.sh — print the prod RDS + ElastiCache subnet CIDRs in
# the exact YAML shape values-prod.yaml expects.
#
# values-prod.yaml ships with placeholder CIDRs (10.10.x.0/24) gated by
# prodGuard.enabled=true so a deploy with placeholders fails noisily.
# This script lifts the real values from AWS so the operator can paste
# them into values-prod.yaml before the first prod deploy.
#
# USAGE:
#   AWS_PROFILE=rafraf-prod AWS_REGION=eu-central-1 \
#     infra/helm/rafraf-backend/scripts/fetch-prod-cidrs.sh
#
# OUTPUT (paste into values-prod.yaml under networkPolicy:):
#
#   rdsCIDRs:
#     - <CIDR_AZ1>
#     - <CIDR_AZ2>
#     - <CIDR_AZ3>
#   redisCIDRs:
#     - <CIDR_AZ1>
#     - <CIDR_AZ2>
#     - <CIDR_AZ3>
#
# REQUIREMENTS:
#   - AWS CLI v2 + credentials with ec2:DescribeSubnets +
#     elasticache:DescribeCacheSubnetGroups + rds:DescribeDBSubnetGroups.
#   - Subnet tagging convention: Tier=database for RDS, Tier=cache for
#     ElastiCache (matches infra/terraform/ networking module). If your
#     prod VPC tags differently, edit the --filters lines below.

set -euo pipefail

REGION="${AWS_REGION:-eu-central-1}"
RDS_TIER_TAG="${RDS_TIER_TAG:-database}"
CACHE_TIER_TAG="${CACHE_TIER_TAG:-cache}"

echo "# Generated by fetch-prod-cidrs.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "# Source: AWS region=${REGION} profile=${AWS_PROFILE:-default}"
echo "# Paste the rdsCIDRs + redisCIDRs blocks into:"
echo "#   infra/helm/rafraf-backend/values-prod.yaml (under networkPolicy:)"
echo ""

# ---------------------------------------------------------------------------
# RDS subnet CIDRs (filter on Tag:Tier=database)
# ---------------------------------------------------------------------------
echo "  rdsCIDRs:"
aws ec2 describe-subnets \
    --region "${REGION}" \
    --filters "Name=tag:Tier,Values=${RDS_TIER_TAG}" \
    --query 'Subnets[*].CidrBlock' \
    --output text \
    | tr '\t' '\n' \
    | sort \
    | sed 's/^/    - /'

echo ""

# ---------------------------------------------------------------------------
# ElastiCache subnet CIDRs (filter on Tag:Tier=cache)
# ---------------------------------------------------------------------------
echo "  redisCIDRs:"
aws ec2 describe-subnets \
    --region "${REGION}" \
    --filters "Name=tag:Tier,Values=${CACHE_TIER_TAG}" \
    --query 'Subnets[*].CidrBlock' \
    --output text \
    | tr '\t' '\n' \
    | sort \
    | sed 's/^/    - /'

echo ""
echo "# After pasting, helm template should pass:"
echo "#   helm template infra/helm/rafraf-backend/ \\"
echo "#     -f infra/helm/rafraf-backend/values.yaml \\"
echo "#     -f infra/helm/rafraf-backend/values-prod.yaml"
echo "# (the prodGuard placeholder check will no longer fire)"
